### ISSUE TITLE
Mac Lost Some Fonts to display error

### ISSUE THREAD

**Issue by HKirito** [ron190/jsql-injection#94250] opened 2021-02-05 02:27 UTC
## Steps to reproduce the problem

  1. mac OS 10.15.7 , java 11 ,commandline “java -jar jsql-injection-v0.83.jar”.
  2. It's working but display error for chinese fonts.

**Comment by ron190** [comment] 2021-02-05 17:58
I'll try to reproduce on Mac+jdk11.
In case I don't manage to reproduce and you have some screenshot, please attach it to the issue.
Thanks for the feedback.

**Comment by ron190** [comment] 2021-02-07 02:47
Regression was introduced by v0.81 on Mac only, no root cause that I can think of.

Anyway the Mac version is such a glitch-fest that any solution has to be found for problems not limited to those:

- Green background on menu
- Blu/Black background on tabs and menu
- Margin on some menu items
- Vertical tabs cropped
- No App icon

`Chinese fonts broken from v0.81 to v0.83 whatever the mac or jdk (mac10.13+jdk15, mac10.8+jdk8)`
<img src=https://user-images.githubusercontent.com/1971480/107133674-14c52600-68eb-11eb-8d0c-459c838fd6ae.png width=300><img src=https://user-images.githubusercontent.com/1971480/107134585-c405fb00-68f3-11eb-93ef-9fd541f02c05.png width=300>

`Chinese fonts fine until v0.80 included (mac10.13+jdk8)`
<img src=https://user-images.githubusercontent.com/1971480/107133402-032e4f00-68e8-11eb-9312-f05392a4144d.png width=300>

`No problem on win/lin+jdk15+v0.83`
<img src=https://user-images.githubusercontent.com/1971480/107133628-9b2d3800-68ea-11eb-814e-4595f618fa85.png width=300>

**Comment by HKirito** [comment] 2021-02-19 09:25
![image](https://user-images.githubusercontent.com/40173190/108485048-74ea9d80-72d7-11eb-9ad0-0b7d87cbb601.png)
like this one

**Comment by HKirito** [comment] 2021-02-19 09:28
![image](https://user-images.githubusercontent.com/40173190/108485331-c3983780-72d7-11eb-86af-08bc9f42e6c4.png)
like this one.

**Comment by ron190** [comment] 2021-02-20 22:25
Most discrepancies I can think about that were encountered on Mac are fixed and will be integrated to the next release. 

Small differences and itches are remaining like different blue colors but worst glitches appear to be gone.

Here's a small teaser:

![image](https://user-images.githubusercontent.com/1971480/108609929-b8293700-73d1-11eb-9f8a-4aced77bab0c.png)

**Comment by ron190** [comment] 2021-02-23 20:55
Fixes are now shipped in v0.84.

**Closed by ron190** 2021-02-23 20:55 UTC
Labels: fixed
